project:
  type: website
  output-dir: docs

website:
  title: "Angelia Miller"
  site-url: https://angeliamiller.dev
  repo-url: https://github.com/AngeliaMiller/angeliamiller.github.io
  navbar:
    title: "Angelia<br>Miller"
    right:
      - text: "Curriculum Vitae"
        href: https://docs.google.com/document/d/e/2PACX-1vStf-zJ6Yu6djAT9383vqFUhasidCpUGUgIhnDB1ibXbryAR8JXl0n2qCa6Rru-4Q5cnr0UYlHzv7e8/pub

format:
  html:
    theme: lux
    css: styles.css
    margin-left: 0.5em
    margin-right: 0.5em
    #linkcolor: 1F9AA8
    # metadata:
    #   pagetitle: "Angelia Miller"
    toc: true


