project:
  type: website
  output-dir: docs

website:
  title: "Angelia Miller"
  site-url: https://angeliamiller.dev
  repo-url: https://github.com/AngeliaMiller/angeliamiller.github.io
  navbar:
    title: "Angelia<br>Miller"
    right:
      - text: "Curriculum Vitae"
        href: am_cv.pdf

format:
  html:
    theme: lux
    css: styles.css
    margin-left: 0.5em
    margin-right: 0.5em
    #linkcolor: 1F9AA8
    # metadata:
    #   pagetitle: "Angelia Miller"
    toc: true


