project:
  type: website
  output-dir: docs

website:
  title: "Angelia Miller"
  favicon: images/wave_favicon2.png
  site-url: https://angeliamiller.dev
  repo-url: https://github.com/AngeliaMiller/angeliamiller.github.io
  navbar:
    title: FALSE
    #"Angelia<br>Miller"
    logo: images/1.png
    logo-alt: "Initials A and M with wave, sun, and mountains in yellow"
    right:
      - text: "Curriculum Vitae"
        href: cv/am_cv.pdf
      - href: https://twitter.com/elmarmills
        icon: "twitter"
      - href: https://github.com/AngeliaMiller
        icon: "github"
  page-footer:
    left: 
      - "Copyright 2022, Angelia Miller"

format:
  html:
    theme: 
       - mystyles.scss
    margin-left: 0.5em
    margin-right: 0.5em
    #linkcolor: 1F9AA8
    # metadata:
    #   pagetitle: "Angelia Miller"
    toc: true


