project:
  type: website
  output-dir: docs

website:
  title: "Angelia Miller"
  site-url: https://angeliamiller.dev
  repo-url: https://github.com/AngeliaMiller/angeliamiller.github.io
  navbar:
    title: "Angelia<br>Miller"
    right:
      - text: "Curriculum Vitae"
        href: https://docs.google.com/document/d/1Op6MLyiURrPKYpV05Z9YyksIWJDLiiMB/edit?usp=sharing&ouid=111597982939495320870&rtpof=true&sd=true

format:
  html:
    theme: lux
    css: styles.css
    margin-left: 0.5em
    margin-right: 0.5em
    #linkcolor: 1F9AA8
    toc: true


