project:
  type: website
  output-dir: docs

website:
  title: "Angelia Miller"
  site-url: https://angeliamiller.dev
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers
      - text: "Presentations"
        href: presentations

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

